"""Add comp generation resources and blacklist

Revision ID: 0a0980f7b6eb
Revises: ed46ff56f083
Create Date: 2018-09-15 14:32:35.554029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0980f7b6eb'
down_revision = 'ed46ff56f083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    comp_gen_table = op.create_table('comp_gen_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_comp_id', sa.Integer(), nullable=True),
    sa.Column('previous_comp_id', sa.Integer(), nullable=True),
    sa.Column('prev_comp_thread_id', sa.String(length=10), nullable=True),
    sa.Column('current_comp_num', sa.Integer(), nullable=True),
    sa.Column('current_bonus_index', sa.Integer(), nullable=True),
    sa.Column('current_OLL_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_comp_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['previous_comp_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_index('ix_competitions_title')
        batch_op.drop_column('userPointResults')

    op.bulk_insert(
        comp_gen_table,
        [
            {
                'current_comp_id'    : 1,
                'previous_comp_id'   : 1,
                'prev_comp_thread_id': '',
                'current_comp_num'   : 293,
                'current_bonus_index': -5,
                'current_OLL_index'  : -1,
            },
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userPointResults', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_competitions_title', ['title'], unique=True)

    op.drop_table('comp_gen_resources')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
