"""Added times_string utility field to UserEventResults.

Revision ID: 5967a351c5f3
Revises: 285503dad691
Create Date: 2018-11-05 14:58:21.650604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5967a351c5f3'
down_revision = '285503dad691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_string', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event_results', schema=None) as batch_op:
        batch_op.drop_column('times_string')

    # ### end Alembic commands ###
