"""Added user ID and comp ID to blacklist table, removed username.

Revision ID: f4a53c1272e5
Revises: 71ad7fd5fb3a
Create Date: 2018-11-25 16:37:02.749970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a53c1272e5'
down_revision = '71ad7fd5fb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comp_event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_blacklist_comp_event_id'), ['comp_event_id'], unique=False)
        batch_op.create_foreign_key('blacklist_comp_event_id_fkey', 'competition_event', ['comp_event_id'], ['id'])
        batch_op.create_foreign_key('blacklist_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_constraint('blacklist_comp_event_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('blacklist_user_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_blacklist_comp_event_id'))
        batch_op.drop_column('user_id')
        batch_op.drop_column('comp_event_id')

    # ### end Alembic commands ###
