"""Added PB flags to UserEventResults.

Revision ID: e3e42c7b6077
Revises: 94c29a81f73a
Create Date: 2018-12-24 11:43:42.408634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e42c7b6077'
down_revision = '94c29a81f73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('was_pb_average', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('was_pb_single', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event_results', schema=None) as batch_op:
        batch_op.drop_column('was_pb_single')
        batch_op.drop_column('was_pb_average')

    # ### end Alembic commands ###
