"""Remove UserSiteRankings competition FK and add timestamp

Revision ID: feb771f719c7
Revises: 3371f5156029
Create Date: 2019-01-11 07:52:49.141903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb771f719c7'
down_revision = '3371f5156029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_site_rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('user_site_rankings_comp_id_fkey', type_='foreignkey')
        batch_op.drop_column('comp_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_site_rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comp_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_site_rankings_comp_id_fkey', 'competitions', ['comp_id'], ['id'])
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
