"""added sum of ranks int columns to UserSiteRankings table

Revision ID: a55e8b8d40ca
Revises: feb771f719c7
Create Date: 2019-01-12 11:26:32.018447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55e8b8d40ca'
down_revision = 'feb771f719c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_site_rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sum_all_average', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sum_all_single', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sum_non_wca_average', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sum_non_wca_single', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sum_wca_average', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sum_wca_single', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_site_rankings', schema=None) as batch_op:
        batch_op.drop_column('sum_wca_single')
        batch_op.drop_column('sum_wca_average')
        batch_op.drop_column('sum_non_wca_single')
        batch_op.drop_column('sum_non_wca_average')
        batch_op.drop_column('sum_all_single')
        batch_op.drop_column('sum_all_average')

    # ### end Alembic commands ###
