"""Add gold, silver, bronze medal flags to UserEventResults.

Revision ID: cf7c80b82dfd
Revises: efa99b5579e6
Create Date: 2019-02-07 10:39:38.314199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7c80b82dfd'
down_revision = 'efa99b5579e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('was_bronze_medal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('was_gold_medal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('was_silver_medal', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event_results', schema=None) as batch_op:
        batch_op.drop_column('was_silver_medal')
        batch_op.drop_column('was_gold_medal')
        batch_op.drop_column('was_bronze_medal')

    # ### end Alembic commands ###
