"""Added ScramblePool model

Revision ID: c92b137ff8be
Revises: cf7c80b82dfd
Create Date: 2019-02-20 12:09:20.213520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92b137ff8be'
down_revision = 'cf7c80b82dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scramble_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('scramble_app', sa.Text(), nullable=True),
    sa.Column('scramble_reddit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scramble_pool')
    # ### end Alembic commands ###
