"""Add bot hit count to metrics

Revision ID: c92d221771c4
Revises: d760c7a84ba3
Create Date: 2019-02-22 12:49:55.796659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92d221771c4'
down_revision = 'd760c7a84ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_hits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_metrics', schema=None) as batch_op:
        batch_op.drop_column('bot_hits')

    # ### end Alembic commands ###
