"""add fmc explanation

Revision ID: e74ccd606cdc
Revises: bbeebbee3456
Create Date: 2019-09-04 10:51:59.543660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74ccd606cdc'
down_revision = 'bbeebbee3456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_solves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fmc_explanation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_solves', schema=None) as batch_op:
        batch_op.drop_column('fmc_explanation')

    # ### end Alembic commands ###
