"""add kinchranks

Revision ID: 2c5f898d5dd7
Revises: 020203030404
Create Date: 2019-09-23 10:25:53.578277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5f898d5dd7'
down_revision = '020203030404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_site_rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_kinchrank', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wca_kinchrank', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_site_rankings', schema=None) as batch_op:
        batch_op.drop_column('wca_kinchrank')
        batch_op.drop_column('all_kinchrank')

    # ### end Alembic commands ###
