"""add non wca only kinchrank

Revision ID: 66f166a908a4
Revises: 2c5f898d5dd7
Create Date: 2019-09-23 11:56:17.358455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f166a908a4'
down_revision = '2c5f898d5dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_site_rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('non_wca_kinchrank', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_site_rankings', schema=None) as batch_op:
        batch_op.drop_column('non_wca_kinchrank')

    # ### end Alembic commands ###
