"""add unique constraint to solve for scramble and event results

Revision ID: 5de7c9b4e68c
Revises: 66f166a908a4
Create Date: 2019-10-13 13:11:53.915868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de7c9b4e68c'
down_revision = '66f166a908a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_solves', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_scramble_user_results', ['scramble_id', 'user_event_results_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_solves', schema=None) as batch_op:
        batch_op.drop_constraint('unique_scramble_user_results', type_='unique')

    # ### end Alembic commands ###
