"""Remove weekly blacklist

Revision ID: 9a8860e9294c
Revises: 0a8384c69050
Create Date: 2020-04-10 16:52:59.629905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8860e9294c'
down_revision = '0a8384c69050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_blacklist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_blacklist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='weekly_blacklist_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='weekly_blacklist_pkey')
    )
    # ### end Alembic commands ###
