"""FK from usersolve to scramble

Revision ID: 0a05bcfefb9e
Revises: 4c270af702ca
Create Date: 2018-06-03 00:06:47.305844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a05bcfefb9e'
down_revision = '4c270af702ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_solves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scramble_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'scrambles', ['scramble_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_solves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('scramble_id')

    # ### end Alembic commands ###
