"""Remove models related to SCS gift cards.

Revision ID: 1e2e5125e920
Revises: 0011223300aa
Create Date: 2024-11-20 20:45:52.741070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e2e5125e920'
down_revision = '0011223300aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_code_recipient_confirm_deny', schema=None) as batch_op:
        batch_op.drop_index('ix_weekly_code_recipient_confirm_deny_comp_id')
        batch_op.drop_index('ix_weekly_code_recipient_confirm_deny_gift_code_id')
        batch_op.drop_index('ix_weekly_code_recipient_confirm_deny_user_id')

    op.drop_table('weekly_code_recipient_confirm_deny')
    op.drop_table('scs_gift_codes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scs_gift_codes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('scs_gift_codes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('gift_code', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scs_gift_codes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('weekly_code_recipient_confirm_deny',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comp_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gift_code_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confirm_code', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('deny_code', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('resolution', postgresql.ENUM('pending', 'confirmed', 'denied', name='resolution'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comp_id'], ['competitions.id'], name='weekly_code_recipient_confirm_deny_comp_id_fkey'),
    sa.ForeignKeyConstraint(['gift_code_id'], ['scs_gift_codes.id'], name='weekly_code_recipient_confirm_deny_gift_code_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='weekly_code_recipient_confirm_deny_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='weekly_code_recipient_confirm_deny_pkey')
    )
    with op.batch_alter_table('weekly_code_recipient_confirm_deny', schema=None) as batch_op:
        batch_op.create_index('ix_weekly_code_recipient_confirm_deny_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_weekly_code_recipient_confirm_deny_gift_code_id', ['gift_code_id'], unique=False)
        batch_op.create_index('ix_weekly_code_recipient_confirm_deny_comp_id', ['comp_id'], unique=False)

    # ### end Alembic commands ###
