"""Add competition generation resources and blacklist

Revision ID: 6bc382b9bb61
Revises: ed46ff56f083
Create Date: 2018-09-13 15:38:31.733633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc382b9bb61'
down_revision = 'ed46ff56f083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comp_gen_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_comp_id', sa.Integer(), nullable=True),
    sa.Column('previous_comp_id', sa.Integer(), nullable=True),
    sa.Column('prev_comp_thread_id', sa.String(length=10), nullable=True),
    sa.Column('current_comp_num', sa.String(length=10), nullable=True),
    sa.Column('current_bonus_index', sa.Integer(), nullable=True),
    sa.Column('current_OLL_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_comp_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['previous_comp_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_column('userPointResults')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userPointResults', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('comp_gen_resources')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
