"""Added Scrambles table with relationship to CompetitionEvent

Revision ID: 88be74c0bf85
Revises: 7790d7218933
Create Date: 2018-06-01 22:28:59.161166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88be74c0bf85'
down_revision = '7790d7218933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrambles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_event_id', sa.Integer(), nullable=True),
    sa.Column('scramble', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competition_event_id'], ['competition_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_column('competition_event', 'scrambles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("none")
    #op.add_column('competition_event', sa.Column('scrambles', sa.TEXT(), nullable=True))
    #op.drop_table('scrambles')
    # ### end Alembic commands ###