"""Add title override and all events flag to comp gen resources

Revision ID: b466c9da106b
Revises: b2855e6c4438
Create Date: 2019-02-21 15:29:57.508078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b466c9da106b'
down_revision = 'b2855e6c4438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comp_gen_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_events', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('title_override', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comp_gen_resources', schema=None) as batch_op:
        batch_op.drop_column('title_override')
        batch_op.drop_column('all_events')

    # ### end Alembic commands ###
