"""Add Reddit ID to UserEventResults

Revision ID: ed46ff56f083
Revises: 011ec2822d26
Create Date: 2018-08-30 22:45:07.636558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed46ff56f083'
down_revision = '011ec2822d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reddit_comment', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event_results', schema=None) as batch_op:
        batch_op.drop_column('reddit_comment')

    # ### end Alembic commands ###
