"""CompGenInfo remove comp num

Revision ID: eed6a6a11005
Revises: 6bc382b9bb61
Create Date: 2018-09-13 22:59:09.408276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed6a6a11005'
down_revision = '6bc382b9bb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comp_gen_resources', schema=None) as batch_op:
        batch_op.drop_column('current_comp_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comp_gen_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_comp_num', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
