"""add active flag to comp

Revision ID: f6c920b9f2cc
Revises: e4dd1ae392b3
Create Date: 2018-05-24 21:34:37.281159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c920b9f2cc'
down_revision = 'e4dd1ae392b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'active')
    # ### end Alembic commands ###
